### ISSUE TITLE
Add Lisp.jl to METADATA

### ISSUE THREAD

**Issue by Ismael-VC** [swadey/Lisp.jl#1]
Please register your awesome package in Julia's official repo so everyone can install it using `Pkg.add`, thanks! :smile:

**Comment by Ismael-VC** [comment]
@swadey see: [Tagging and Publishing Your Package](http://julia.readthedocs.org/en/latest/manual/packages/#tagging-and-publishing-your-package)

**Comment by swadey** [comment]
hey ismael.  I figured this was more a toy project for myself, but I can do it if it's helpful for folks.

**Comment by Ismael-VC** [comment]
Yes, please do, I'd love if more people could also help hack on this, some people in [Twitter](https://twitter.com/ismael_vc/status/684609940653096960) showed a positive reaction to Lisp.jl and even Gerald Jay Sussman was apparently interested in something like this for Julia, see: [here](https://gitter.im/JuliaLang/julia?at=568d06109a5f8fe839216d6d)

Thank's in advance! :smile:

**Comment by Ismael-VC** [comment]
I was trying to load Lisp in v0.4.2 but it currently fails. I will open an issue for that, and try to solve it.

**Comment by swadey** [comment]
hopefully I did that right.  I think it's in the publish queue waiting for metadata merge.

**Comment by Ismael-VC** [comment]
Great! :smile:
