### ISSUE TITLE
Make , alias of tuple

### ISSUE THREAD

**Issue by Ismael-VC** [swadey/Lisp.jl#10]
Hy lang uses this:

``` lisp
=> (, 1 2 3)
(1, 2, 3)
```
- http://docs.hylang.org/en/stable/tutorial.html#hy-is-a-lisp-flavored-python

currently we do this:

``` lisp
lisp> (tuple 1 2 3)
(1,2,3)
```

I'm not sure if this conflicts with the backquote syntax:
- http://www.lispworks.com/documentation/HyperSpec/Body/02_df.htm

I think clojure uses ~ am I right?

**Comment by Ismael-VC** [comment]
Or do you think a literal tuple syntax would be more useful instead?

**Comment by Ismael-VC** [comment]
What about `#(1 2 3)`?

**Comment by Ismael-VC** [comment]
Currently `'[1 2 3]` and `'(1 2 3)` are interchangeable, should a possible `#(1 2 3)`  be the same as
 `#[1 2 3]`?

**Comment by swadey** [comment]
This is interesting.  Many lisps use `#` as a reader-macro dispatch character.  I think clojure uses this character for reader dispatch and I believe they use `#()` as an anonymous function dispatch as in `#(+ %1 %2)` which translates into `(fn [a b] (+ a b))`

Perhaps we use either the `(, _ _)` or use tuple dispatch `#tuple{}` or `#tuple()` and just properly implement constructor dispatch.  The word `tuple` can be any constructor in that case.   

What do you think?

**Comment by swadey** [comment]
just pushed a version that includes an experimental version of reader dispatch.  two further steps would be necessary to support tuples:
1. tuples have to become first-class iterables 
2. a reader function needs to be attached.  I'll do something along this line tomorrow.
