### ISSUE TITLE
Floats are not recognized?

### ISSUE THREAD

**Issue by zlaus** [swadey/Lisp.jl#13]
trying to input a floating point variable gives an Error. Same when using LispREPL

julia> lisp"(+ 3.0 2.0)"
ERROR: UndefVarError: .0 not defined

or am i simply missing something?

by the way: awesome work! Julia with s expressions has the potential to be mindblowing awesome :)

**Comment by Ismael-VC** [comment]
@zlaus the documentation and tests are still sparce and just starting, sorry about that, there is only one example of this in the tests:
- https://github.com/swadey/LispSyntax.jl/blob/master/test/runtests.jl#L21

``` julia
@expect LispSyntax.read("3.0d") == 3.0
```

The literal for 64 bits floating points values **as of now** is currently postfixed with a `d` (I was going to suggest this weekend to let it be the same as Julia as you expected), feel free update the documentation yourself if you like, it can be done from the web interface.

I'll have spare time to document all the literals until the weekend.

Thanks for reporting this.

@swadey could you change the title of this issue so as not to forget to document this?

**Comment by Ismael-VC** [comment]
``` julia
julia> using LispREPL

lisp> (+ 3.0d 2.0d)
5.0
```

**Comment by Ismael-VC** [comment]
This is the current definition for parsing doubles:
- https://github.com/swadey/LispSyntax.jl/blob/master/src/parser.jl#L13

``` julia
doubley = p"[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?[dD]" > (x -> parse(Float64, x[1:end-1]))
```

**Comment by swadey** [comment]
yeah, ismael is right.  The current syntax for floats is `3.0f` and doubles `3.0d`.

**Comment by zlaus** [comment]
Thank you! Had to be somthing trivial.
I created a pull request and added this information to the quick intro :)
