### ISSUE TITLE
Add ReadTheDocs commit webhook.

### ISSUE THREAD

**Issue by Ismael-VC** [swadey/Lisp.jl#15]
This allows to build the documentation (update PDF, website, etc.) automagically when a push or merge is made to the documentation in the master branch:  
- http://read-the-docs.readthedocs.org/en/latest/webhooks.html

Also @swadey could you add me as a mantainer of the documentation at readthethocs please? My readthedocs user is `Ismael-VC`, thanks!

**Comment by swadey** [comment]
Done!  Thanks for volunteering.

**Comment by Ismael-VC** [comment]
Thank you! :+1:
