### ISSUE TITLE
Load a program from file

### ISSUE THREAD

**Issue by FemtoEmacs** [swadey/Lisp.jl#18]
I could not find instructions for loading a program from file. I wrote this fib benchmark test in a fib.jl file:

(defn fib(n)
  (if (< n 2) 1 (+ (fib (- n 1))
     (fib (- n 2))) ))

I couldn't find any example on how to include it in the REPL. I tried:

lisp> (include "fib.jl")
ERROR: LoadError: syntax: missing separator in tuple
 in include at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:320
while loading /Users/edu500ac/LispSyntax.jl/src/fib.jl, in expression starting on line 1

Is there a Lisp version of include?

I never used Julia because I don't like the syntax. LispSyntax could be a solution for people who are used to Lisp or emacs lisp, and don't want to learn an enterily new and unfriendly syntax. But it is necessary a better documentation.

**Comment by swadey** [comment]
currently, there is no `include` operator in the REPL.  It wouldn't be too hard to add.  If you're interested in trying; I'd be happy to help but it does require writing a bit of julia code :)
