### ISSUE TITLE
Getting this running on Julia 0.6 / 07 ?

### ISSUE THREAD

**Issue by MasonProtter** [swadey/Lisp.jl#19]
Hey, so what is required to get this working with the current versions of Julia? I suppose first we'd need [PEGParser](https://github.com/abeschneider/PEGParser.jl) to be updated?

**Comment by swadey** [comment]
hey sorry about the delay.  That's basically it.  I did port it to 0.6 and it does basically seem to work.

**Comment by MasonProtter** [comment]
No worries!

> I did port it to 0.6 and it does basically seem to work
 
Did you port PEGParser or LispSyntax?

**Comment by swadey** [comment]
LispSyntax

**Comment by MasonProtter** [comment]
Do you have any plans to merge this port you did?

**Comment by swadey** [comment]
yes, the plan is to do this when 0.7 is released and stable.  The current 0.6 port is somewhat broken and I haven't had a chance to debug.  It's all about to get OBE'd by 0.7.

**Comment by davidroberson** [comment]
bump
