### ISSUE TITLE
Make LispSyntax filetype

### ISSUE THREAD

**Issue by MasonProtter** [swadey/Lisp.jl#28]
To make this nicer for people to use, I think it'd be cool to make a special filetype for julia with lispsyntax so that it can have it's own syntax highlighting / indentation rules and so that when it's `include`'d, the lisp parser is used on it instead of the julia parser. This would also allow users to avoid using the string macro directly. 

I'd be interested in working on this sometime in the next couple of months.

**Comment by c42f** [comment]
Currently `Base.include()` can't be extended in this way and I'm not sure that makes sense to change.  But we can easily have another function name. Did you notice https://github.com/swadey/LispSyntax.jl/pull/24?

**Comment by MasonProtter** [comment]
> Did you notice #24?

I did not!
