### ISSUE TITLE
Bug for starting REPL

### ISSUE THREAD

**Issue by PallHaraldsson** [swadey/Lisp.jl#35]
Hi,

I like your package, and while I got the custom REPL to work (and your repl.jl file to work, by hacking it) I'm not sure why the README instructed way doesn't work:

```
julia> using LispSyntax
julia> LispSyntax.init_repl()
ERROR: UndefVarError: init_repl not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:13
 [2] top-level scope at REPL[30]:1
```

It's simply as if the include for the repl.jl file is ineffective, at least for me in Julia 1.3.1. I thought maybe an export was missing, but then that shouldn't be needed as fully qualified. I see you dropped/moved the REPL, but seems you changed your mind by adding back. I thought of making a doc or code PR, just not sure if your want this working or people should use the other (unregistered) package. I'm also trying to learn from this about Julia, and why failing here.

**Comment by PallHaraldsson** [comment]
I now see #33 and maybe a new version just needs to be tagged?

**Comment by swadey** [comment]
yeah, this was added in 0.2.1 which hasn't been registered.  I will do this shortly.  Thanks.

**Comment by PallHaraldsson** [comment]
#36 can be closed too, I just don't think I can.
