### ISSUE TITLE
Name this lisp!

### ISSUE THREAD

**Issue by Ismael-VC** [swadey/Lisp.jl#8]
We should really think in a name it would be useful so we can call it with scripts and such, ie

``` bash
$ julisp foo.jlisp arg1 arg3
```

Or something like that!

cc: @swadey  @MichaelHatherly I could organize a poll if that is ok, what do you think?

**Comment by swadey** [comment]
I maintain that this is michael's decision :)

**Comment by MichaelHatherly** [comment]
What kind of name are we wanting? Something "unsurprising" like @Ismael-VC's `julisp`, or maybe `jisp`. Or perhaps something a bit more obscure / creative?

**Comment by Ismael-VC** [comment]
:+1: obscure creative! :smile: look at pixie and hy, specially hy, I like they word play :sparkles: :
- Hylarious 
- The Hyve (yes, the Hy community prides itself in appending Hy to everything) 
- Hypster (Hy programmer)
- hyland
- HY-ISMS, etc.

It isn't named after either Python nor Lisp, also Pixie, my suggestions are pretty unsurprising as Michael points out, I'll think in some other names.

**Comment by swadey** [comment]
a couple of constraints:
1. we can rename LispREPL.jl without issue, but the name of this package probably can't change at least not easily.
2. probably should be searchable
