### ISSUE TITLE
Enable github home page.

### ISSUE THREAD

**Issue by Ismael-VC** [swadey/Lisp.jl#9]
This would allow us to easily create a project home page as these are autogenerated and edited with markdown, I would like to ask repo access to edit it further (don't know if it works with git PRs normal workflow).

Example using hack theme:
- http://ismael-vc.github.io/LispSyntax.jl

See #8 for naming.

cc: @swadey

**Comment by swadey** [comment]
done!

**Comment by Ismael-VC** [comment]
great thanks! :D
